class MyCustomError(Exception):
    pass

try:
    raise MyCustomError("This is a custom error")
except MyCustomError as e:
    print("Caught custom error:", e)
